# Generated by Django 3.2 on 2021-05-14 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("work_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_sheet",
                to="work_tracker.job",
            ),
        ),
    ]
